services:
  web:
    build:
      context: .
    container_name: itam-web
    ports:
      - 8080:80
    environment:
      DB_HOST: metro.proxy.rlwy.net
      DB_PORT: 37915
      DB_NAME: railway
      DB_USER: root
      DB_PASS: plDXUCJHPOqdBbbrscIxjyxchxdtMzQd
    depends_on: []  
